/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeviceDetail: typeof import('./src/components/DeviceDetail.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
  }
}
